#!/usr/bin/env python
# -*- coding: utf-8 -*-
# Copyright (C) 2012 sakito <sakito@sakito.com>

from waflib import Logs
import dircache
import os


def configure(ctx):
    for cmd in ('hg', 'git'):
        try:
            ctx.find_program(cmd)
        except ctx.errors.ConfigurationError:
            ctx.to_log('%s was not found' % cmd)


def build(ctx):
    Logs.info('update')
    dir_list = dircache.listdir('.')
    for var in dir_list:
        if os.path.isdir(var):
            print '----------'
            print var
            os.chdir(var)
            if os.path.exists('.hg'):
                ctx.exec_command('hg pull; hg up')
            elif os.path.exists('.git'):
                ctx.exec_command('git pull; git fetch')

            os.chdir('..')
